[KAFKA]
bootstrap_servers = 46.202.167.130:9094,46.202.167.130:9194,46.202.167.130:9294
topic = product_view
starting_offsets = earliest
security_protocol = SASL_PLAINTEXT
sasl_mechanism = PLAIN
sasl_jaas_config = org.apache.kafka.common.security.plain.PlainLoginModule required username="kafka" password="${KAFKA_PASSWORD}";

[POSTGRES]
host = postgres
port = 5432
database = glamira_db
user = admin
password = ${POSTGRES_PASSWORD}

[SPARK]
app_name = StreamMart_ProductViews
checkpoint_dir = /tmp/checkpoint/product_views_v2
trigger_processing_time = 10 seconds